#
# @see https://hub.docker.com/_/redis/
#
FROM redis:3.2.11
MAINTAINER willrain <willrain@gmail.com>

# 이미지 생성
## docker build -t global-nexus:9003/gssg-redis .

# global-nexus push
## docker push global-nexus:9003/gssg-redis

# global-nexus pull
## docker pull global-nexus:9003/gssg-redis

# 실행
## docker run -d -it --rm --name gssg-redis global-nexus:9003/gssg-redis
## docker exec -it gssg-redis bash

