<?php
return array (
    'backend' => array ('frontName' => 'bo',),
    'db' =>array (
        'connection' => array (
            'indexer' => array (
                'host' => '10.203.7.62',
                'dbname' => 'gssgdb_new',
                'username' => 'gssg',
                'password' => 'gssg12#',
                'active' => '1',
                'persistent' => NULL,
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
            ),
            'default' => array (
                'host' => '10.203.7.62',
                'dbname' => 'gssgdb_new',
                'username' => 'gssg',
                'password' => 'gssg12#',
                'active' => '1',
                'model' => 'mysql4',
                'engine' => 'innodb',
                'initStatements' => 'SET NAMES utf8;',
            ),
        ),
        'slave_connection' => array (
            'default' => array (
                'host' => '10.203.7.61:3307',
                'dbname' => 'gssgdb_new',
                'username' => 'gssg',
                'password' => 'gssg12#',
                'active' => '1',
            ),
        ),
        'table_prefix' => '',
    ),
    'crypt' => array ( 'key' => '647a43ac1fb80a04c8e8e0ad32c2c84b',),
    'resource' => array (
        'default_setup' => array ( 'connection' => 'default',),
    ),
    'x-frame-options' => 'SAMEORIGIN',
    'MAGE_MODE' => 'production',
    'cache_types' => array (
        'config' => 1,
        'layout' => 0,
        'block_html' => 1,
        'collections' => 1,
        'reflection' => 1,
        'db_ddl' => 1,
        'eav' => 1,
        'full_page' => 1,
        'config_integration' => 1,
        'config_integration_api' => 1,
        'target_rule' => 1,
        'translate' => 1,
        'config_webservice' => 1,
    ),
    'install' => array ( 'date' => 'Thu, 14 Sep 2017 07:44:03 +0000',),
    'queue' => array (
        'amqp' => array (
            'host' => '',
            'port' => '',
            'user' => '',
            'password' => '',
            'virtualhost' => '/',
            'ssl' => '',
        ),
    ),
    'session' => array (
        'save' => 'redis',
        'redis' => array (
            'host' => '202.8.175.89',
            'port' => '6379',
            'password' => 'root!@#',
            'timeout' => '2.5',
            'persistent_identifier' => '',
            'database' => '13',
            'compress_data' => '0',
            'compression_threshold' => '2048',
            'compression_library' => 'gzip',
            'log_level' => '1',
            'max_concurrency' => '6',
            'break_after_frontend' => '5',
            'break_after_adminhtml' => '30',
            'first_lifetime' => '600',
            'bot_first_lifetime' => '60',
            'bot_lifetime' => '7200',
            'disable_locking' => '0',
            'min_lifetime' => '60',
            'max_lifetime' => '2592000',
        ),
    ),
    'cache' => array (
        'frontend' => array (
            'default' => array (
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => array (
                    'server' => '202.8.175.89',
                    'port' => '6379',
                    'password' => 'root!@#',
                    'persistent' => '',
                    'database' => '14',
                    'force_standalone' => '0',
                    'connect_retries' => '1',
                    'read_timeout' => '10',
                    'automatic_cleaning_factor' => '0',
                    'compress_data' => '1',
                    'compress_tags' => '1',
                    'compress_threshold' => '20480',
                    'compression_lib' => 'gzip',
                ),
            ),
            'page_cache' => array(
                'backend' => 'Cm_Cache_Backend_Redis',
                'backend_options' => array(
                    'server' => '202.8.175.89',
                    'port' => '6379',
                    'password' => 'root!@#',
                    'persistent' => '',
                    'database' => '15',
                    'force_standalone' => '0',
                    'connect_retries' => '1',
                    'read_timeout' => '10',
                    'automatic_cleaning_factor' => '0',
                    'compress_data' => '0',
                    'compress_tags' => '1',
                    'compress_threshold' => '20480',
                    'compression_lib' => 'gzip',
                )
            )
        ),
    ),
    'zone' => 'new',
    'mage_root_dir' => '/data01/webroot/www',
);